
All:
	go get github.com/fatih/structs
	go get github.com/go-redis/redis
	go get github.com/yosssi/gmq/mqtt
	cd ./cmd &&go build --ldflags="-w -s" -o ../build/message-handler 
clean:
	rm build/message-handler  
