
All:
	go get github.com/buger/jsonparser
	go get github.com/eclipse/paho.mqtt.golang 
	go get github.com/garyburd/redigo/redis
	go get github.com/google/uuid
	go get github.com/gorilla/mux
	go get github.com/jinzhu/gorm
	go get github.com/aws/aws-sdk-go/aws
	go get github.com/lib/pq 
	go get github.com/patrickmn/go-cache
	go get github.com/sirupsen/logrus 
	cd ./cmd &&go build --ldflags="-w -s" -o ../build/app-orchestration-server

clean:
	rm build/app-orchestration-server
