Base_template = {
    { proxy_url = "^/users",        openfaas_name = "scale-user"     },
    { proxy_url = "^/account",      openfaas_name = "scale-user"     },
    { proxy_url = "^/customers",    openfaas_name = "scale-user"     },
    { proxy_url = "^/vendors",      openfaas_name = "scale-user"     },
    { proxy_url = "^/tasks",        openfaas_name = "scale-task"     },
    { proxy_url = "^/solutions",    openfaas_name = "scale-solution" },
    { proxy_url = "^/roles",        openfaas_name = "scale-role"     },
    { proxy_url = "^/permissions",  openfaas_name = "scale-role"     },
    { proxy_url = "^/resources",    openfaas_name = "scale-role"     }, 
    { proxy_url = "^/devices",      openfaas_name = "scale-device"   },
    { proxy_url = "^/device-group", openfaas_name = "scale-device"   },
    { proxy_url = "^/applications", openfaas_name = "scale-app"      },
    { proxy_url = "^/api",          openfaas_name = "scale-other"    },
    { proxy_url = "^/audit",        openfaas_name = "scale-other"    },
    { proxy_url = "^/deployment",   openfaas_name = "scale-other"    },
    { proxy_url = "^/info",         openfaas_name = "scale-other"    },
    { proxy_url = "^/models",       openfaas_name = "scale-other"    },
    { proxy_url = "^/registry",     openfaas_name = "scale-other"    },
    { proxy_url = "^/services",     openfaas_name = "scale-other"    },
    { proxy_url = "^/storage",      openfaas_name = "scale-other"    },
}
